### ISSUE TITLE
ERROR:  Incompatible shapes: [32,17] vs. [31,17]

### ISSUE THREAD

**Issue by yzmean** [spallas/time-attention#5]
Hi，when I run train.py , there is some error. Can you help me.

(tensorflow-gpu) root@fudan:~/anaconda3/envs/tensorflow-gpu/time-attention# (tensorflow-gpu) root@fudan:~/anaconda3/envs/tensorflow-gpu/time-attention# python train.py
2019-09-10 20:00:16.350976: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-10 20:00:16.519047: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-10 20:00:16.519848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties:
name: Tesla M40 major: 5 minor: 2 memoryClockRate(GHz): 1.112
pciBusID: 0000:00:08.0
totalMemory: 11.92GiB freeMemory: 11.81GiB
2019-09-10 20:00:16.519891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2019-09-10 20:00:16.837772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11434 MB memory) -> physical GPU (device: 0, name: Tesla M40, pci bus id: 0000:00:08.0, compute capability: 5.2)
====================================== EPOCH 0 ======================================
Traceback (most recent call last):
  File "/root/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/root/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/root/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,17] vs. [31,17]

**Comment by spallas** [comment]
Can you give us further details on the line in the code where the exception is generated?
